define(['angular'], function (angular) {
  'use strict';

  /**
   * @ngdoc function
   * @name walletHubApp.controller:FourCtrl
   * @description
   * # FourCtrl
   * Controller of the walletHubApp
   */
  angular.module('walletHubApp.controllers.FourCtrl', [])
    .controller('FourCtrl', function ($scope) {
      $scope.data = [{
        "country": "Iran",
        "first_name": "Randy",
        "last_name": "Sullivan"
      }, {
        "country": "Ethiopia",
        "first_name": "Russell",
        "last_name": "Ryan"
      }, {
        "country": "Colombia",
        "first_name": "Stephanie",
        "last_name": "Cooper"
      }, {
        "country": "Brazil",
        "first_name": "Wanda",
        "last_name": "Stevens"
      }, {
        "country": "Poland",
        "first_name": "Gerald",
        "last_name": "Morris"
      }, {
        "country": "Russia",
        "first_name": "Philip",
        "last_name": "Jackson"
      }, {
        "country": "Philippines",
        "first_name": "Eric",
        "last_name": "Harper"
      }, {
        "country": "China",
        "first_name": "James",
        "last_name": "Gilbert"
      }, {
        "country": "Philippines",
        "first_name": "Brian",
        "last_name": "Johnston"
      }, {
        "country": "Papua New Guinea",
        "first_name": "Diane",
        "last_name": "Henry"
      }, {
        "country": "Palestinian Territory",
        "first_name": "Fred",
        "last_name": "Sanchez"
      }, {
        "country": "Nicaragua",
        "first_name": "George",
        "last_name": "Mills"
      }, {
        "country": "China",
        "first_name": "Martha",
        "last_name": "Porter"
      }, {
        "country": "Costa Rica",
        "first_name": "George",
        "last_name": "Freeman"
      }, {
        "country": "Portugal",
        "first_name": "Dennis",
        "last_name": "Peterson"
      }, {
        "country": "Egypt",
        "first_name": "Kathleen",
        "last_name": "Rodriguez"
      }, {
        "country": "Iran",
        "first_name": "Philip",
        "last_name": "Evans"
      }, {
        "country": "China",
        "first_name": "Joshua",
        "last_name": "Richards"
      }, {
        "country": "China",
        "first_name": "Sharon",
        "last_name": "Mills"
      }, {
        "country": "Uruguay",
        "first_name": "Frank",
        "last_name": "White"
      }, {
        "country": "Colombia",
        "first_name": "Matthew",
        "last_name": "Alvarez"
      }, {
        "country": "Philippines",
        "first_name": "Howard",
        "last_name": "Duncan"
      }, {
        "country": "United Kingdom",
        "first_name": "Jeremy",
        "last_name": "Jacobs"
      }, {
        "country": "Portugal",
        "first_name": "Jennifer",
        "last_name": "Hansen"
      }, {
        "country": "Philippines",
        "first_name": "Christina",
        "last_name": "Gonzalez"
      }, {
        "country": "United States",
        "first_name": "Lawrence",
        "last_name": "Nelson"
      }, {
        "country": "Peru",
        "first_name": "Dennis",
        "last_name": "Ruiz"
      }, {
        "country": "Kenya",
        "first_name": "Christine",
        "last_name": "Payne"
      }, {
        "country": "Brazil",
        "first_name": "Diana",
        "last_name": "Wagner"
      }, {
        "country": "Poland",
        "first_name": "Brandon",
        "last_name": "Ramos"
      }, {
        "country": "Kazakhstan",
        "first_name": "Nancy",
        "last_name": "Owens"
      }, {
        "country": "Yemen",
        "first_name": "Daniel",
        "last_name": "Fowler"
      }, {
        "country": "Greece",
        "first_name": "Melissa",
        "last_name": "Rose"
      }, {
        "country": "China",
        "first_name": "Deborah",
        "last_name": "West"
      }, {
        "country": "China",
        "first_name": "Martha",
        "last_name": "Stewart"
      }, {
        "country": "Japan",
        "first_name": "Russell",
        "last_name": "Simmons"
      }, {
        "country": "Vietnam",
        "first_name": "Benjamin",
        "last_name": "Elliott"
      }, {
        "country": "China",
        "first_name": "Mildred",
        "last_name": "Weaver"
      }, {
        "country": "Nigeria",
        "first_name": "Edward",
        "last_name": "Black"
      }, {
        "country": "Spain",
        "first_name": "Martin",
        "last_name": "Little"
      }, {
        "country": "China",
        "first_name": "Kevin",
        "last_name": "Coleman"
      }, {
        "country": "Czech Republic",
        "first_name": "Donna",
        "last_name": "Palmer"
      }, {
        "country": "Liberia",
        "first_name": "Peter",
        "last_name": "Reed"
      }, {
        "country": "China",
        "first_name": "Annie",
        "last_name": "Henderson"
      }, {
        "country": "Indonesia",
        "first_name": "Arthur",
        "last_name": "Lopez"
      }, {
        "country": "Thailand",
        "first_name": "Gerald",
        "last_name": "Freeman"
      }, {
        "country": "Russia",
        "first_name": "Nancy",
        "last_name": "Hansen"
      }, {
        "country": "Portugal",
        "first_name": "William",
        "last_name": "Green"
      }, {
        "country": "Indonesia",
        "first_name": "Carol",
        "last_name": "Stephens"
      }, {
        "country": "Brazil",
        "first_name": "Timothy",
        "last_name": "Burke"
      }];
    });
});
